### ISSUE TITLE
Native fetch throws errors

### ISSUE THREAD

**Issue by enjoylife** [fusionjs/fusion-plugin-universal-events#183]
### Type of issue
Bug
### Description
If  you follow the getting started guide and register fetch via the window,

```
// ...
  __BROWSER__ && app.register(FetchToken, window.fetch)
```
this will fail in chrome with “Uncaught TypeError: Illegal invocation”, as the fetch is later executed during `flush`  in the context of current object.

For this to work properly, it must be executed in the context of window, https://stackoverflow.com/a/10743608/1403990

A naive change is to modify the constructor of the UniversalEmitter:

```
this.fetch = fetch; // from
this.fetch = fetch.bind(window); // to
```

but i'm not sure how this would play out in older browsers, different fetch implementations, etc.

One other thing. This bug, is unreported to devs as the try catch surrounding the call to the fetch, swallows the error.

```
 try {
      const res = await this.fetch('/_events', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({items}),
      });

      if (!res.ok) {
        // sending failed so put the logs back into storage
        this.storage.addToStart(...items);
      }
    } catch (e) {
      // There should be some noise here during development
     // that this branch is being executed...
      this.storage.addToStart(...items);
    }

**Comment by AlexMSmithCA** [comment]
Thanks for filing this!

We should avoid binding `window` to any provided fetch implementation, as we make no assumptions on the context for the function call.  For example, `unfetch` is fairly popular to provide better browser support.

I'll create a PR to update our documentation to avoid registering `window.fetch` directly.  A simple solution would be to register an already bound `window.fetch`.  Something like:

```
const app = new App(/*some root*/);
__BROWSER__ && app.register(FetchToken, fetch.bind(window));
```

Closing this, but happy to revisit if you have other thoughts.
